<?php

namespace ContainerS5lvLU6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_C5FF1dYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.C5FF1dY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.C5FF1dY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CampaignController::delete' => ['privates', '.service_locator.7v9CP8S', 'get_ServiceLocator_7v9CP8SService', true],
            'App\\Controller\\CampaignController::edit' => ['privates', '.service_locator.7v9CP8S', 'get_ServiceLocator_7v9CP8SService', true],
            'App\\Controller\\CampaignController::index' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\CampaignController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\CampaignController::show' => ['privates', '.service_locator.rYUDYfm', 'get_ServiceLocator_RYUDYfmService', true],
            'App\\Controller\\ParticipantController::delete' => ['privates', '.service_locator.Q4XTF_1', 'get_ServiceLocator_Q4XTF1Service', true],
            'App\\Controller\\ParticipantController::edit' => ['privates', '.service_locator.Q4XTF_1', 'get_ServiceLocator_Q4XTF1Service', true],
            'App\\Controller\\ParticipantController::index' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ParticipantController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ParticipantController::show' => ['privates', '.service_locator.FedAEPz', 'get_ServiceLocator_FedAEPzService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\CampaignController:delete' => ['privates', '.service_locator.7v9CP8S', 'get_ServiceLocator_7v9CP8SService', true],
            'App\\Controller\\CampaignController:edit' => ['privates', '.service_locator.7v9CP8S', 'get_ServiceLocator_7v9CP8SService', true],
            'App\\Controller\\CampaignController:index' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\CampaignController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\CampaignController:show' => ['privates', '.service_locator.rYUDYfm', 'get_ServiceLocator_RYUDYfmService', true],
            'App\\Controller\\ParticipantController:delete' => ['privates', '.service_locator.Q4XTF_1', 'get_ServiceLocator_Q4XTF1Service', true],
            'App\\Controller\\ParticipantController:edit' => ['privates', '.service_locator.Q4XTF_1', 'get_ServiceLocator_Q4XTF1Service', true],
            'App\\Controller\\ParticipantController:index' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ParticipantController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ParticipantController:show' => ['privates', '.service_locator.FedAEPz', 'get_ServiceLocator_FedAEPzService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\CampaignController::delete' => '?',
            'App\\Controller\\CampaignController::edit' => '?',
            'App\\Controller\\CampaignController::index' => '?',
            'App\\Controller\\CampaignController::new' => '?',
            'App\\Controller\\CampaignController::show' => '?',
            'App\\Controller\\ParticipantController::delete' => '?',
            'App\\Controller\\ParticipantController::edit' => '?',
            'App\\Controller\\ParticipantController::index' => '?',
            'App\\Controller\\ParticipantController::new' => '?',
            'App\\Controller\\ParticipantController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\CampaignController:delete' => '?',
            'App\\Controller\\CampaignController:edit' => '?',
            'App\\Controller\\CampaignController:index' => '?',
            'App\\Controller\\CampaignController:new' => '?',
            'App\\Controller\\CampaignController:show' => '?',
            'App\\Controller\\ParticipantController:delete' => '?',
            'App\\Controller\\ParticipantController:edit' => '?',
            'App\\Controller\\ParticipantController:index' => '?',
            'App\\Controller\\ParticipantController:new' => '?',
            'App\\Controller\\ParticipantController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
