<?php

namespace ContainerS5lvLU6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FedAEPzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FedAEPz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FedAEPz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'participant' => ['privates', '.errored..service_locator.FedAEPz.App\\Entity\\Participant', NULL, 'Cannot autowire service ".service_locator.FedAEPz": it needs an instance of "App\\Entity\\Participant" but this type has been excluded in "config/services.yaml".'],
        ], [
            'participant' => 'App\\Entity\\Participant',
        ]);
    }
}
