<?php

namespace ContainerS5lvLU6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Q4XTF1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Q4XTF_1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Q4XTF_1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'participant' => ['privates', '.errored..service_locator.Q4XTF_1.App\\Entity\\Participant', NULL, 'Cannot autowire service ".service_locator.Q4XTF_1": it needs an instance of "App\\Entity\\Participant" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'participant' => 'App\\Entity\\Participant',
        ]);
    }
}
