<?php

namespace ContainerS5lvLU6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RYUDYfmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rYUDYfm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rYUDYfm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'campaign' => ['privates', '.errored..service_locator.rYUDYfm.App\\Entity\\Campaign', NULL, 'Cannot autowire service ".service_locator.rYUDYfm": it needs an instance of "App\\Entity\\Campaign" but this type has been excluded in "config/services.yaml".'],
        ], [
            'campaign' => 'App\\Entity\\Campaign',
        ]);
    }
}
