<?php

namespace ContainerS5lvLU6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCampaign2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.rYUDYfm.App\Entity\Campaign' shared service.
     *
     * @return \App\Entity\Campaign
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.rYUDYfm": it needs an instance of "App\\Entity\\Campaign" but this type has been excluded in "config/services.yaml".');
    }
}
