<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerS5lvLU6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerS5lvLU6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerS5lvLU6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerS5lvLU6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerS5lvLU6\App_KernelDevDebugContainer([
    'container.build_hash' => 'S5lvLU6',
    'container.build_id' => '7bdd4bf1',
    'container.build_time' => 1681805472,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerS5lvLU6');
